name: Detect and Report Terraform Drift
description: Detect infrastructure drift and create/update GitHub issues for visibility
inputs:
  github_token:
    required: true
    type: string
    description: 'GitHub token for API access'
  plan_exit_code:
    required: true
    type: string
    description: 'Terraform plan exit code (0=no changes, 2=drift detected)'
  output_summary:
    required: true
    type: string
    description: 'Terraform plan summary/output for issue body'

description: Detect and Report Terraform Drift
runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        source "${{ github.action_path }}/../scripts/error-handler.sh"
        source "${{ github.action_path }}/../scripts/validate-inputs.sh"
        
        validate_required "github_token" "${{ inputs.github_token }}"
        validate_exit_code "${{ inputs.plan_exit_code }}"
        validate_summary "${{ inputs.output_summary }}"
    
    # If changes are detected, create a new issue
    - name: Create Drift Issue
      if: ${{ inputs.plan_exit_code == '2' }}
      uses: actions/github-script@v7
      env:
        SUMMARY: "${{ inputs.output_summary }}"
      with:
          github-token: ${{ inputs.github_token }}
          script: |
            const body = `${process.env.SUMMARY}`;
            const title = 'ðŸš¨ Terraform Configuration Drift Detected';
            const creator = 'github-actions[bot]'
          
            // Look for existing drift issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              creator: creator
            })
            
            const driftIssue = issues.data.find(issue => issue.title === title);
              
            if(driftIssue) {
              if (driftIssue.body === body) {
                console.log('â„¹ï¸ Drift issue exists with identical content')
              } else {
                console.log('âš ï¸ Updating existing drift issue')
                await github.rest.issues.update({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  issue_number: driftIssue.number,
                  body: body
                })
              }
            } else {
              console.log('ðŸ†• Creating new drift detection issue')
              await github.rest.issues.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: title,
                body: body,
                labels: ['terraform', 'drift']
              })
            }
            
    # If no changes detected, close any open drift issues
    - name: Close Drift Issue (if resolved)
      if: ${{ inputs.plan_exit_code == '0' }}
      uses: actions/github-script@v7
      with:
          github-token: ${{ inputs.github_token }}
          script: |
            const title = 'ðŸš¨ Terraform Configuration Drift Detected';
            const creator = 'github-actions[bot]'
          
            // Look for existing drift issue
            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'open',
              creator: creator
            })
            
            const driftIssue = issues.data.find(issue => issue.title === title);
              
            if(driftIssue) {
              console.log('âœ… Closing resolved drift issue')
              await github.rest.issues.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: driftIssue.number,
                state: 'closed'
              })
            } else {
              console.log('âœ“ No drift detected and no open drift issues')
            }
             
    # Mark the workflow as failed if drift detected
    - name: Fail on Drift
      if: ${{ inputs.plan_exit_code == '2' }}
      shell: bash
      run: |
        echo "::error::Configuration drift detected - infrastructure has deviated from code"
        exit 1