name: Terraform Plan --Destroy
description: Generate a Terraform destroy plan (preview resource removal)
inputs:
  environment:
    required: true
    type: string
    description: 'Environment name (e.g., dev, staging, prod)'
  working_dir:
    required: true
    type: string
    description: 'Working directory for Terraform operations'
  params_dir:
    required: true
    type: string
    description: 'Directory containing variable files'
outputs:
  exitcode:
    description: 'Terraform plan exit code (0=no changes, 1=error, 2=changes detected)'
    value: ${{ steps.tf-plan-destroy.outputs.exitcode }}
runs:
  using: "composite"
  steps:
    - name: Validate Inputs
      shell: bash
      run: |
        source "${{ github.action_path }}/../scripts/error-handler.sh"
        source "${{ github.action_path }}/../scripts/validate-inputs.sh"
        
        validate_plan_inputs \
          "${{ inputs.environment }}" \
          "${{ inputs.working_dir }}" \
          "${{ inputs.params_dir }}" \
          "${{ github.workspace }}"
    
    - name: Terraform Plan --Destroy
      shell: bash
      id: tf-plan-destroy
      working-directory: ${{ inputs.working_dir }}
      env:
        TF_INPUT: "false"
        TF_IN_AUTOMATION: "true"
      run: |
        source "${{ github.action_path }}/../scripts/error-handler.sh"
        
        log_group "Terraform Plan --Destroy"
        warn_destructive "plan destroy for" "${{ inputs.environment }}"
        
        local_exitcode=0
        terraform plan -destroy \
          -input=false \
          -detailed-exitcode \
          -var-file="${{ github.workspace }}/${{ inputs.params_dir }}/${{ inputs.environment }}-variables.tfvars" \
          -out "${{ inputs.environment }}.plan.tfplan" || local_exitcode=$?
        
        log_group_end
        
        echo "exitcode=$local_exitcode" >> $GITHUB_OUTPUT
        handle_terraform_error "plan -destroy" "$local_exitcode"
